# Generated by Django 4.2.7 on 2023-11-25 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSpot',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchPost',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('game_date', models.DateTimeField(help_text='게임 날짜')),
                ('game_type',
                 models.CharField(choices=[('single', '단식'),
                                           ('mix_single', '단식(성별 무관)'),
                                           ('w_double', '여복'),
                                           ('m_double', '남복'),
                                           ('mix_double', '복식(성별 무관)')],
                                  help_text='게임 타입',
                                  max_length=100)),
                ('created_at',
                 models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content', models.TextField(blank=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('game_spot',
                 models.ForeignKey(
                     help_text='게임 장소',
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     to='match.gamespot')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
