# Generated by Django 4.2.7 on 2023-12-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='sevage.jpeg', null=True, upload_to=''),
        ),
    ]
